export type Zone = 'uka' | 'kula' | 'kai';

export type PlantData = {
  id: string;
  name: string;
  scientific: string;
  zone: Zone;
  image: string;
  description: string;
  distribution: string;
  landscape: string;
  care: string;
  cultural: string;
  category: string;
  rarity: string;
};

export const PLANT_DATA: PlantData[] = [
  {
    id: 'kalo',
    name: 'Kalo',
    scientific: 'Colocasia esculenta',
    zone: 'uka',
    image: '/plants/kalo.jpg',
    description: 'Large succulent herb with heart-shaped leaves (lau) and thick underground corms.',
    distribution: 'Found mostly in wet valleys and cultivated taro patches (lo\u02bbi) across all main islands.',
    landscape: 'Best in full sun to partial shade in wet, muddy conditions or water gardens.',
    care: 'Requires constant moisture or flooded conditions and rich, organic soil.',
    cultural: 'The primordial ancestor of the Hawaiian people (H\u0101loanakalaukapalili). A sacred staple food source; every part of the plant is used, primarily for making poi.',
    category: 'Canoe Plant',
    rarity: 'Common / Cultivated',
  },
  {
    id: 'kukui',
    name: 'Kukui',
    scientific: 'Aleurites moluccanus',
    zone: 'kula',
    image: '/plants/kukui.jpg',
    description: 'Large canopy tree with distinctive silvery-green, maple-like leaves.',
    distribution: 'Forms a major component of the mesic valley canopy across all main islands.',
    landscape: 'Excellent large shade tree. Highly visible in landscapes due to its unique light-colored foliage.',
    care: 'Fast-growing tree. Needs ample room to grow, well-draining soil, and moderate watering.',
    cultural: 'The symbol of enlightenment and wisdom. Nut oil was burned for light (rama) or used for medicine; the nuts are roasted into a condiment (\u02bbinamona); bark and nuts used for dyes.',
    category: 'Canoe Plant',
    rarity: 'Common',
  },
  {
    id: 'ohia',
    name: '\u02bb\u014chi\u02bba Lehua',
    scientific: 'Metrosideros polymorpha',
    zone: 'uka',
    image: '/plants/ohia.jpg',
    description: 'Highly variable tree or shrub with brush-like flowers (usually red, but can be yellow, orange, or white) and rounded leaves.',
    distribution: 'Found from sea level to tree line across various ecosystems from dry to wet forests on all main islands.',
    landscape: 'Excellent structural or specimen plant, windbreak, or focal point.',
    care: 'Slow-growing but tough. Prefers full sun and well-drained soil; protect from Rapid \u02bb\u014chi\u02bba Death vectors.',
    cultural: 'Sacred to Pele (volcano goddess) and Laka (goddess of hula). The wood was used for temple images (ki\u02bbi), spears, and tools; flowers and leaf buds (liko) are prized for lei.',
    category: 'Endemic',
    rarity: 'Common',
  },
  {
    id: 'pohinahina',
    name: 'P\u014dhinahina',
    scientific: 'Vitex rotundifolia',
    zone: 'kai',
    image: '/plants/pohinahina.webp',
    description: 'Low-growing, sprawling coastal shrub with rounded, silvery-blue-green leaves that smell like sage when crushed, and small purple flower clusters.',
    distribution: 'Found on sandy beaches, dunes, and rocky coastal areas across the Hawaiian chain.',
    landscape: 'Outstanding for coastal xeriscaping, erosion control, bank stabilization, and low-maintenance groundcover.',
    care: 'Thrives in full sun, heat, sandy or rocky soil, and requires very little water once established. Highly salt and wind tolerant.',
    cultural: 'Leaves were used medicinally in steam baths or wrapped around the head to relieve headaches. Flowers and leaves are occasionally used for lei.',
    category: 'Indigenous',
    rarity: 'Common',
  },
  {
    id: 'hapuu',
    name: 'H\u0101pu\u02bbu',
    scientific: 'Cibotium glaucum',
    zone: 'uka',
    image: '/plants/hapuu.jpg',
    description: 'Large tree fern with a thick, fibrous trunk and massive, soft green, arching fronds.',
    distribution: 'Naturally dominates the understory of wet, montane rainforests, especially on Hawai\u02bbi island.',
    landscape: 'Provides a dramatic tropical, architectural focal point in shaded landscapes.',
    care: 'Requires a shady, humid environment with damp, organic-rich soil. The trunk must be kept moist via regular misting in warmer, lower-elevation areas.',
    cultural: 'The soft, woolly pulu (hairs at the base of fronds) was historically collected as a dressing for wounds and for stuffing mattresses/pillows. The starchy core was cooked as a famine food.',
    category: 'Endemic',
    rarity: 'Common',
  },
  {
    id: 'loulu',
    name: 'Loulu',
    scientific: 'Pritchardia spp.',
    zone: 'kai',
    image: '/plants/loulu.jpg',
    description: 'Fan palms with large, stiff, fan-shaped leaves and large clusters of round green-to-black fruits.',
    distribution: 'Varies by species; found in coastal valleys to wet mountain ridges across specific islands.',
    landscape: 'Stunning architectural accent palm for a unique Hawaiian signature look.',
    care: 'Prefers full sun to partial shade and sharp, well-drained soil. Water requirements and wind/salt tolerance vary by species.',
    cultural: 'Fronds were traditionally used for thatching roofs, making fans (pe\u02bbahi), and umbrellas. The young, unripe seeds (h\u0101wane) were eaten as a delicacy.',
    category: 'Endemic',
    rarity: 'Varies',
  },
  {
    id: 'naupaka',
    name: 'Naupaka kahakai',
    scientific: 'Scaevola taccada',
    zone: 'kai',
    image: '/plants/naupaka.webp',
    description: 'Robust, fleshy coastal shrub with bright green, succulent leaves and distinctive white \u2018half-flowers\u2019 that look split in half, followed by white berries.',
    distribution: 'Ubiquitous along sandy strands, rocky coastlines, and beach fronts throughout Hawai\u02bbi.',
    landscape: 'Essential beach-front hedge plant. Incredible salt, wind, and drought tolerance.',
    care: 'Prefers full sun and sandy, sharp-draining soil. Requires minimal care and very little water once established.',
    cultural: 'Famous in Hawaiian mythology regarding separated lovers. The succulent leaves can be crushed to prevent dive masks from fogging; white berries and pith were used for traditional crafts.',
    category: 'Indigenous',
    rarity: 'Common',
  },
  {
    id: 'ulu',
    name: 'Ulu',
    scientific: 'Artocarpus altilis',
    zone: 'kula',
    image: '/plants/ulu.jpg',
    description: 'Large, majestic tree with deeply lobed, glossy dark green leaves, producing large, starchy, green-skinned fruits.',
    distribution: 'Cultivated extensively around settlements and moist valleys across all main islands.',
    landscape: 'Stately specimen tree that offers deep shade and abundant food production.',
    care: 'Needs plenty of space, full sun, and regular watering in rich, deep, well-draining soil. Sensitive to frost and extreme cold.',
    cultural: 'A vital staple food crop across Polynesia. The sticky milky sap (kolu) was used as birdlime to catch birds for featherwork and as a sealant. The wood was used for canoes, bowls, and surfboards.',
    category: 'Canoe Plant',
    rarity: 'Common / Cultivated',
  },
  {
    id: 'lai',
    name: 'L\u0101\u02bbi',
    scientific: 'Cordyline fruticosa',
    zone: 'kula',
    image: '/plants/lai.jpg',
    description: 'Erect, woody plant with long, smooth, blade-like green leaves growing in dense, terminal clusters.',
    distribution: 'Widely cultivated and naturalized around homes, valleys, and agricultural borders across all islands.',
    landscape: 'Excellent foundation plant, accent, or informal hedge. Brings a classic cultural aesthetic.',
    care: 'Very easy to grow from stem cuttings. Prefers moist, well-drained soil in full sun to partial shade. Low maintenance.',
    cultural: 'Highly sacred plant used to ward off negative energy and bring good fortune. Extensively used for hula skirts, wrapping food for cooking (laulau), sandals, thatch, and diverse medicinal remedies.',
    category: 'Canoe Plant',
    rarity: 'Common',
  },
  {
    id: 'limu',
    name: 'Limu',
    scientific: 'Multiple species',
    zone: 'kai',
    image: '/plants/limu.jpg',
    description: 'Edible seaweed gathered from the ocean. A vital part of traditional Hawaiian diet.',
    distribution: 'Found in coastal waters and tide pools around the Hawaiian islands.',
    landscape: 'N/A — gathered from the ocean.',
    care: 'N/A — wild harvested.',
    cultural: 'Traditional Hawaiian food source gathered from the sea. Used in poke, soups, and as a condiment.',
    category: 'Traditional Food',
    rarity: 'Common',
  },
  {
    id: 'kupukupu',
    name: 'Kupukupu',
    scientific: 'Nephrolepis exaltata',
    zone: 'uka',
    image: '/kupukupu.jpg',
    description: 'A lush sword fern with long, arching fronds and dense clumps of dark green leaflets.',
    distribution: 'Found in shaded, moist forest understories and along stream banks across all main islands.',
    landscape: 'Excellent groundcover for shaded areas, hanging baskets, or naturalized understory plantings.',
    care: 'Thrives in partial to full shade with consistently moist, rich organic soil. Resilient and fast-growing.',
    cultural: 'In Hawaiian culture, the kupukupu is associated with growth and resilience. Young fronds (fiddleheads) were sometimes used in hula lei.',
    category: 'Indigenous',
    rarity: 'Common',
  },
];

export const PLANT_ALIASES: Record<string, string[]> = {
  kalo:      ['kalo', 'taro', 'colocasia', 'esculenta'],
  kukui:     ['kukui', 'candlenut', 'aleurites', 'moluccanus', 'candle nut'],
  ohia:      ['ohia', '\u02bb\u014chi\u02bba', 'lehua', 'metrosideros', 'polymorpha', 'ohia lehua'],

  pohinahina:['pohinahina', 'vitex', 'rotundifolia', 'beach vitex'],
  hapuu:     ['hapuu', 'h\u0101pu\u02bbu', 'cibotium', 'glaucum', 'tree fern'],
  loulu:     ['loulu', 'pritchardia', 'fan palm', 'hawaiian palm'],
  naupaka:   ['naupaka', 'naupaka kahakai', 'scaevola', 'taccada', 'beach naupaka'],

  ulu:       ['ulu', 'breadfruit', 'artocarpus', 'altilis'],
  lai:       ['lai', 'l\u0101\u02bbi', 'cordyline', 'fruticosa', 'ti', 'ti plant'],
  limu:      ['limu', 'seaweed', 'algae', 'seaweeds'],
  kupukupu:  ['kupukupu', 'nephrolepis', 'exaltata', 'sword fern'],
};
