export type Zone = 'uka' | 'kula' | 'kai';

export type PlantData = {
  id: string;
  name: string;
  scientific: string;
  zone: Zone;
  image: string;
  description: string;
  distribution: string;
  landscape: string;
  care: string;
  cultural: string;
  category: string;
  rarity: string;
};

export const PLANT_DATA: PlantData[] = [
  {
    id: 'kalo',
    name: 'Kalo',
    scientific: 'Colocasia esculenta',
    zone: 'uka',
    image: '/plants/kalo.jpg',
    description: 'Large succulent herb with heart-shaped leaves (lau) and thick underground corms.',
    distribution: 'Found mostly in wet valleys and cultivated taro patches (loʻi) across all main islands.',
    landscape: 'Best in full sun to partial shade in wet, muddy conditions or water gardens.',
    care: 'Requires constant moisture or flooded conditions and rich, organic soil.',
    cultural: 'The primordial ancestor of the Hawaiian people (Hāloanakalaukapalili). A sacred staple food source; every part of the plant is used, primarily for making poi.',
    category: 'Canoe Plant',
    rarity: 'Common / Cultivated',
  },
  {
    id: 'kukui',
    name: 'Kukui',
    scientific: 'Aleurites moluccanus',
    zone: 'kula',
    image: '/plants/kukui.jpg',
    description: 'Large canopy tree with distinctive silvery-green, maple-like leaves.',
    distribution: 'Forms a major component of the mesic valley canopy across all main islands.',
    landscape: 'Excellent large shade tree. Highly visible in landscapes due to its unique light-colored foliage.',
    care: 'Fast-growing tree. Needs ample room to grow, well-draining soil, and moderate watering.',
    cultural: 'The symbol of enlightenment and wisdom. Nut oil was burned for light (rama) or used for medicine; the nuts are roasted into a condiment (ʻinamona); bark and nuts used for dyes.',
    category: 'Canoe Plant',
    rarity: 'Common',
  },
  {
    id: 'ohia',
    name: 'ʻŌhiʻa Lehua',
    scientific: 'Metrosideros polymorpha',
    zone: 'uka',
    image: '/plants/ohia.jpg',
    description: 'Highly variable tree or shrub with brush-like flowers (usually red, but can be yellow, orange, or white) and rounded leaves.',
    distribution: 'Found from sea level to tree line across various ecosystems from dry to wet forests on all main islands.',
    landscape: 'Excellent structural or specimen plant, windbreak, or focal point.',
    care: 'Slow-growing but tough. Prefers full sun and well-drained soil; protect from Rapid ʻŌhiʻa Death vectors.',
    cultural: 'Sacred to Pele (volcano goddess) and Laka (goddess of hula). The wood was used for temple images (kiʻi), spears, and tools; flowers and leaf buds (liko) are prized for lei.',
    category: 'Endemic',
    rarity: 'Common',
  },
  {
    id: 'palapalai',
    name: 'Palapalai',
    scientific: 'Microlepia strigosa',
    zone: 'kula',
    image: '/plants/palapalai.jpg',
    description: 'A beautiful, delicate-looking indigenous fern with light green, hairy fronds that grow up to 3 feet long.',
    distribution: 'Found in mesic forest understories and shaded valleys across the main islands.',
    landscape: 'Excellent shaded groundcover, understory accent, or container plant.',
    care: 'Prefers partial to full shade, rich organic soil, and regular watering to keep the soil consistently moist.',
    cultural: 'One of the primary plants dedicated to Laka. Highly significant in hula culture; extensively woven into lei poʻo (head lei) and used to adorn the hula altar (kuahu).',
    category: 'Indigenous',
    rarity: 'Common',
  },
  {
    id: 'pohinahina',
    name: 'Pōhinahina',
    scientific: 'Vitex rotundifolia',
    zone: 'kai',
    image: '/plants/pohinahina.webp',
    description: 'Low-growing, sprawling coastal shrub with rounded, silvery-blue-green leaves that smell like sage when crushed, and small purple flower clusters.',
    distribution: 'Found on sandy beaches, dunes, and rocky coastal areas across the Hawaiian chain.',
    landscape: 'Outstanding for coastal xeriscaping, erosion control, bank stabilization, and low-maintenance groundcover.',
    care: 'Thrives in full sun, heat, sandy or rocky soil, and requires very little water once established. Highly salt and wind tolerant.',
    cultural: 'Leaves were used medicinally in steam baths or wrapped around the head to relieve headaches. Flowers and leaves are occasionally used for lei.',
    category: 'Indigenous',
    rarity: 'Common',
  },
  {
    id: 'hapuu',
    name: 'Hāpuʻu',
    scientific: 'Cibotium glaucum',
    zone: 'uka',
    image: '/plants/hapuu.jpg',
    description: 'Large tree fern with a thick, fibrous trunk and massive, soft green, arching fronds.',
    distribution: 'Naturally dominates the understory of wet, montane rainforests, especially on Hawaiʻi island.',
    landscape: 'Provides a dramatic tropical, architectural focal point in shaded landscapes.',
    care: 'Requires a shady, humid environment with damp, organic-rich soil. The trunk must be kept moist via regular misting in warmer, lower-elevation areas.',
    cultural: 'The soft, woolly pulu (hairs at the base of fronds) was historically collected as a dressing for wounds and for stuffing mattresses/pillows. The starchy core was cooked as a famine food.',
    category: 'Endemic',
    rarity: 'Common',
  },
  {
    id: 'loulu',
    name: 'Loulu',
    scientific: 'Pritchardia spp.',
    zone: 'kai',
    image: '/plants/loulu.jpg',
    description: 'Fan palms with large, stiff, fan-shaped leaves and large clusters of round green-to-black fruits.',
    distribution: 'Varies by species; found in coastal valleys to wet mountain ridges across specific islands.',
    landscape: 'Stunning architectural accent palm for a unique Hawaiian signature look.',
    care: 'Prefers full sun to partial shade and sharp, well-drained soil. Water requirements and wind/salt tolerance vary by species.',
    cultural: 'Fronds were traditionally used for thatching roofs, making fans (peʻahi), and umbrellas. The young, unripe seeds (hāwane) were eaten as a delicacy.',
    category: 'Endemic',
    rarity: 'Varies (Many species are rare/endangered)',
  },
  {
    id: 'naupaka',
    name: 'Naupaka kahakai',
    scientific: 'Scaevola taccada',
    zone: 'kai',
    image: '/plants/naupaka.webp',
    description: 'Robust, fleshy coastal shrub with bright green, succulent leaves and distinctive white "half-flowers" that look split in half, followed by white berries.',
    distribution: 'Ubiquitous along sandy strands, rocky coastlines, and beach fronts throughout Hawaiʻi.',
    landscape: 'Essential beach-front hedge plant. Incredible salt, wind, and drought tolerance.',
    care: 'Prefers full sun and sandy, sharp-draining soil. Requires minimal care and very little water once established.',
    cultural: 'Famous in Hawaiian mythology regarding separated lovers. The succulent leaves can be crushed to prevent dive masks from fogging; white berries and pith were used for traditional crafts.',
    category: 'Indigenous',
    rarity: 'Common',
  },
  {
    id: 'aaliia',
    name: 'ʻAʻaliʻi',
    scientific: 'Dodonaea viscosa',
    zone: 'kula',
    image: '/plants/aalii.jpg',
    description: 'Highly resilient shrub or small tree with sticky leaves and showy, papery, multi-winged seed capsules that range from cream to deep red/pink.',
    distribution: 'Extremely adaptive; found from coastal dunes to alpine scrub zones on all main islands.',
    landscape: 'Excellent for windbreaks, erosion control, or mass hillside plantings.',
    care: 'Exceptionally hardy. Thrives in poor soil, intense sun, heavy winds, and requires minimal water once established.',
    cultural: 'The durable wood was used for house posts, spears, and tools. The colorful, papery seed capsules are highly prized for lei making and dry floral arrangements.',
    category: 'Indigenous',
    rarity: 'Common',
  },
  {
    id: 'ulu',
    name: 'Ulu',
    scientific: 'Artocarpus altilis',
    zone: 'kula',
    image: '/plants/ulu.jpg',
    description: 'Large, majestic tree with deeply lobed, glossy dark green leaves, producing large, starchy, green-skinned fruits.',
    distribution: 'Cultivated extensively around settlements and moist valleys across all main islands.',
    landscape: 'Stately specimen tree that offers deep shade and abundant food production.',
    care: 'Needs plenty of space, full sun, and regular watering in rich, deep, well-draining soil. Sensitive to frost and extreme cold.',
    cultural: 'A vital staple food crop across Polynesia. The sticky milky sap (kolu) was used as birdlime to catch birds for featherwork and as a sealant. The wood was used for canoes, bowls, and surfboards.',
    category: 'Canoe Plant',
    rarity: 'Common / Cultivated',
  },
  {
    id: 'lai',
    name: 'Lāʻī',
    scientific: 'Cordyline fruticosa',
    zone: 'kula',
    image: '/plants/lai.jpg',
    description: 'Erect, woody plant with long, smooth, blade-like green leaves growing in dense, terminal clusters.',
    distribution: 'Widely cultivated and naturalized around homes, valleys, and agricultural borders across all islands.',
    landscape: 'Excellent foundation plant, accent, or informal hedge. Brings a classic cultural aesthetic.',
    care: 'Very easy to grow from stem cuttings. Prefers moist, well-drained soil in full sun to partial shade. Low maintenance.',
    cultural: 'Highly sacred plant used to ward off negative energy and bring good fortune. Extensively used for hula skirts, wrapping food for cooking (laulau), sandals, thatch, and diverse medicinal remedies.',
    category: 'Canoe Plant',
    rarity: 'Common',
  },
  {
    id: 'kupukupu',
    name: 'Kupukupu',
    scientific: 'Nephrolepis cordifolia',
    zone: 'uka',
    image: '/kupukupu.jpg',
    description: 'A sword fern with erect fronds (1–2 ft. tall). It is terrestrial but can be epiphytic. Distinguishable by underground tubers on its stolons.',
    distribution: 'Found throughout the tropics; in Hawaiʻi, common on all main islands in mesic to wet forests.',
    landscape: 'Great as an accent plant around stones, mass groundcover, or at the base of rock walls.',
    care: 'Plant in full sun or partial shade. Needs well-drained soil; water daily but do not allow to sit in standing water to prevent yellowing.',
    cultural: 'Symbolizes learning and sprouting knowledge (as kupu means to sprout); often used to decorate hula altars and in lei making.',
    category: 'Fern',
    rarity: 'Common',
  },
  // ── Weekly-earned plants ──────────────────────────────────────────────────
  {
    id: 'alula',
    name: 'Ālula',
    scientific: 'Brighamia insignis',
    zone: 'kai',
    image: '/plants/alula.jpg',
    description: 'An unusual succulent shrub resembling a "cabbage on a stick," featuring a thick, fleshy stem topped by a rosette of broad green leaves and fragrant, cream-to-yellow tubular flowers.',
    distribution: 'Historically endemic to the steep, windward sea cliffs of Kauaʻi and Niʻihau.',
    landscape: 'Excellent focal point, container specimen, or rock garden accent for coastal or modern tropical designs.',
    care: 'Needs extremely well-draining soil (like a cactus mix) and full sun to partial shade. Water very sparingly; highly prone to spider mites.',
    cultural: 'Historically used in traditional local medicine. Today, it serves as a powerful international symbol of Hawaiian plant conservation.',
    category: 'Shrub / Succulent',
    rarity: 'Critically Endangered (Extinct in the wild; relies completely on human cultivation and hand-pollination)',
  },
  {
    id: 'kokio',
    name: 'Kokiʻo keʻokeʻo',
    scientific: 'Hibiscus immaculatus',
    zone: 'kula',
    image: '/plants/kokio.jpg',
    description: 'A rare native white hibiscus shrub or small tree featuring glossy, dark green leaves and pure, pristine white flowers with a distinctive white staminal column. The flowers are delicately fragrant.',
    distribution: 'Endemic strictly to the moist, isolated valleys and sea cliffs of Molokaʻi.',
    landscape: 'Makes a stunning ornamental specimen tree, accent plant, or privacy screen in semi-shaded, moist garden areas.',
    care: 'Thrives in rich, moist, well-draining soil. Requires regular watering and prefers partial shade to full sun.',
    cultural: 'Flowers were traditionally used for personal adornment (hei) and occasionally in traditional medicinal remedies.',
    category: 'Shrub / Small Tree',
    rarity: 'Critically Endangered (One of the rarest hibiscus species in the world)',
  },
  {
    id: 'kooloaula',
    name: 'Koʻoloaʻula',
    scientific: 'Abutilon menziesii',
    zone: 'kai',
    image: '/plants/kooloaula.jpg',
    description: 'An upright shrub with beautiful, velvety, silvery-green heart-shaped leaves and contrasting, nodding, bell-shaped flowers ranging from maroon to dark red.',
    distribution: 'Endemic to dry, low-elevation plains and slopes on Lānaʻi, Maui, Oʻahu, and Hawaiʻi Island.',
    landscape: 'Perfect for xeriscaping, rock gardens, or dry borders due to its exceptional drought tolerance and striking foliage color contrast.',
    care: 'Requires full sun and very well-drained soil. Water sparingly once established; highly drought-resistant and susceptible to root rot if overwatered.',
    cultural: 'The attractive red flowers are occasionally used in modern lei making; highly valued for native dry-land ecosystem restoration.',
    category: 'Shrub',
    rarity: 'Endangered (Threatened by urban development and wild fires)',
  },
  {
    id: 'maile',
    name: 'Maile',
    scientific: 'Alyxia stellata',
    zone: 'uka',
    image: '/plants/maile.jpg',
    description: 'A twining, woody vine or scrambling shrub with glossy green leaves and small green-yellow flowers. It emits an iconic, sweet vanilla-like scent when the bark is lightly stripped or crushed.',
    distribution: 'Found throughout mesic and wet forests on all main islands except Niʻihau and Kahoʻolawe.',
    landscape: 'Ideal as a container plant, trellis climber, or ground cover in shaded to partially sunny garden areas.',
    care: 'Requires well-draining soil, partial shade, and moderate watering. It can be slow-growing and sensitive to root disturbance.',
    cultural: 'Highly sacred and prized for making lei maile; associated with Laka (goddess of hula), used in hula altars, weddings, and peace-making ceremonies.',
    category: 'Vine / Shrub',
    rarity: 'Culturally rare and declining in the wild due to over-harvesting and habitat loss',
  },
  {
    id: 'limu',
    name: 'Limu kohu',
    scientific: 'Asparagopsis taxiformis',
    zone: 'kai',
    image: '/plants/limu.jpg',
    description: 'A beautiful, soft red algae with a feathery, plume-like appearance. It grows in fluffy tufts from a creeping, root-like base and ranges in color from grayish-pink to bright magenta or dark red. It has a very potent, sharp iodine aroma.',
    distribution: 'Found globally in tropical and subtropical waters. In Hawaiʻi, it thrives on all main islands along shallow reef flats and rocky platforms (papa) heavily impacted by constant wave action and rushing water.',
    landscape: 'Not applicable — it is a marine organism and cannot be grown in a standard backyard or terrestrial garden landscape.',
    care: 'Wild-harvested by carefully pinching off the upright fronds while leaving the basal roots intact. To prepare, it is soaked overnight in water to mellow its intense pungency, lightly salted, and traditionally rolled into tight balls for long-term storage.',
    cultural: 'Known as the "supreme," "choice," or "pleasing" seaweed. It is the most highly prized edible limu in Hawaiʻi, famously used to flavor poke, raw fish, and stews. Featured in legendary chants and songs like Ka Uluwehi O Ke Kai. Traditionally, women (wahine) were the supreme experts in gathering it. Medicinally, its high iron content was used to treat blood ailments like anemia.',
    category: 'Marine Algae (Red Algae / Limu)',
    rarity: 'Uncommon / Threatened (Wild populations are declining rapidly due to habitat degradation, climate change, and unsustainable harvesting)',
  },
];

export const PLANT_ALIASES: Record<string, string[]> = {
  kalo: [
    'kalo', 'taro', 'colocasia', 'colocasia esculenta', 'esculenta',
    'hawaiian taro', 'wetland taro',
  ],
  kukui: [
    'kukui', 'candlenut', 'candle nut', 'kukui nut',
    'aleurites', 'aleurites moluccanus', 'moluccanus',
  ],
  ohia: [
    'ohia', 'ohia lehua', 'ohi a lehua', 'lehua',
    'metrosideros', 'metrosideros polymorpha', 'polymorpha',
  ],
  palapalai: [
    'palapalai', 'microlepia', 'microlepia strigosa', 'strigosa',
    'hawaiian fern', 'lace fern',
  ],
  pohinahina: [
    'pohinahina', 'beach vitex', 'vitex', 'vitex rotundifolia', 'rotundifolia',
    'pohina', 'beach naupaka vitex',
  ],
  hapuu: [
    'hapuu', 'hapu u', 'tree fern', 'hawaiian tree fern',
    'cibotium', 'cibotium glaucum', 'glaucum',
  ],
  loulu: [
    'loulu', 'hawaiian palm', 'fan palm', 'native palm',
    'pritchardia', 'pritchardia spp',
  ],
  naupaka: [
    'naupaka', 'naupaka kahakai', 'beach naupaka', 'coastal naupaka',
    'scaevola', 'scaevola taccada', 'taccada',
  ],
  aaliia: [
    'aaliia', 'a alii', "a'alii", 'aalii',
    'dodonaea', 'dodonaea viscosa', 'viscosa',
    'hopbush', 'hop bush',
  ],
  ulu: [
    'ulu', 'breadfruit', 'bread fruit',
    'artocarpus', 'artocarpus altilis', 'altilis',
  ],
  lai: [
    'lai', 'ti', 'ti plant', 'ti leaf', 'la i',
    'cordyline', 'cordyline fruticosa', 'fruticosa',
    'good luck plant',
  ],
  kupukupu: [
    'kupukupu', 'sword fern', 'nephrolepis', 'nephrolepis cordifolia', 'cordifolia',
    'boston fern', 'kupuku',
  ],
  alula: [
    'alula', 'olulu', 'vulcan palm', 'cabbage on a stick',
    'brighamia', 'brighamia insignis', 'insignis',
  ],
  kokio: [
    'kokio', 'kokio keokeо', 'kokio keokeo', 'white hibiscus', 'native hibiscus',
    'hibiscus immaculatus', 'immaculatus',
    'pua aloalo', 'hawaiian hibiscus',
  ],
  kooloaula: [
    'kooloaula', 'ko oloaula', "ko'oloaula", 'red abutilon',
    'abutilon', 'abutilon menziesii', 'menziesii',
  ],
  maile: [
    'maile', 'alyxia', 'alyxia stellata', 'alyxia oliviformis', 'stellata',
    'lei maile',
  ],
  limu: [
    'limu', 'limu kohu', 'seaweed', 'red algae',
    'asparagopsis', 'asparagopsis taxiformis', 'taxiformis',
    'hawaiian seaweed',
  ],
};
